#!/bin/sh

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
set -eu

# Redirect STDERR to STDOUT
exec 2>&1

# Make environnement variables accessibles
[ -r /etc/envvars ] && . /etc/envvars

# Start worker queue
exec su-exec www-data php /var/www/artisan queue:work database --queue=high,standard,low --sleep=3 --tries=3

# This exit code will be sent as the first parameter to the finish script
exit 1

